# Generated by Django 2.0.5 on 2018-07-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('Ariana', 'Ariana'), ('Beja', 'Beja'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Jendouba', 'Jendouba'), ('Gabes', 'Gabes'), ('Gafsa', 'Gafsa'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kebili', 'Kebili'), ('Le Kef', 'Le Kef'), ('La Manouba', 'La Manouba'), ('Mahdia', 'Mahdia'), ('Medenine', 'Medenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tunis', 'Tunis'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Zaghouan', 'Zaghouan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('Ariana', 'Ariana'), ('Beja', 'Beja'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Jendouba', 'Jendouba'), ('Gabes', 'Gabes'), ('Gafsa', 'Gafsa'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kebili', 'Kebili'), ('Le Kef', 'Le Kef'), ('La Manouba', 'La Manouba'), ('Mahdia', 'Mahdia'), ('Medenine', 'Medenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tunis', 'Tunis'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Zaghouan', 'Zaghouan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
